sudo: required
dist: trusty
language: node_js
node_js:
 - "6.10.3"
 
apt:
 sources:
  - google-chrome
 packages:
  - google-chrome-stable
  - google-chrome-beta

before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

install:
 - sudo apt-get update

before_script:
 - cd loganalyzer
 - npm install -g @angular/cli
 - npm install
 - ng build
 - sleep 5
 
script:
 - ng test --watch=false