sudo: required
matrix:
    include:
        - language: java
          jdk: openjdk8
          services:
            - elasticsearch
          before_script:
            - cd ./testloganalyzer
            - sleep 30
          script:
            - mvn clean install -Dspring.profiles.active=dev
          after_script:
            - cd ..
          
        - language: node_js
          node_js: 8
          addons:
             apt:
                 sources:
                    - google-chrome
                 packages:
                    - google-chrome-stable
                    - google-chrome-beta
          before_install:
             - export CHROME_BIN=chromium-browser
             - export DISPLAY=:99.0
             - sh -e /etc/init.d/xvfb start
          before_script:
            - cd ./testloganalyzer-gui
            - npm install -g @angular/cli
            - npm install
          script:
            - ng build --prod --aot
            - ng test
          after_script:
            - cd ..
