sudo: required
language: node_js
node_js:
 - "6.10.3"
 
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

before_script:
 - cd loganalyzer
 - npm install -g @angular/cli
 - npm install
 - ng build
 - sleep 5
 
script:
 - ng test --watch=false && ng e2e