sudo: required
matrix:
    include:
        - language: java
          jdk: openjdk8
          before_script:
            - cd ./testloganalyzer
          script:
            - mvn clean install -Dspring.profiles.active=prod -DskipTests
          after_script:
            - cd ..
          
        - language: node_js
          node_js: 8
          before_script:
            - cd ./testloganalyzer-gui
            - npm install -g @angular/cli
            - npm install
          script:
            - ng build --prod --aot
            - ng test
          after_script:
            - cd ..