sudo: required
language: node_js
node_js:
 - "6.10.1"
 
before_script:
 - npm install -g @angular-cli
 - cd loganalyzer
 - npm install
 
script:
 - ng set --global warnings.packageDeprecation=false
 - ng build --dev