version: 2
jobs:
  build:
    working_directory: ~/LOGANALYZER
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: angular-cli-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: angular-cli-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: npm install
